[package]
name = "ya"
version = "0.6.0"
edition = "2021"
default-run = "ya"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "build.rs"

[build-dependencies]
clap = { version = "4.3.23", features = ["derive", "cargo"], optional = true }
clap_complete = { version = "4.3.2", optional = true }
handlebars = { version = "4.3.7", optional = true }
serde_json = { version = "1.0.104", optional = true }

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.23", features = ["derive", "cargo"] }
colored = "2.0.4"
serde_yaml = "0.9.25"
home = { version = "0.5.5", optional = true }
clap_complete = { version = "4.3.2", optional = true }
handlebars = {version = "4.3.7", optional = true }
serde_json = { version = "1.0.104", optional = true }

[dev-dependencies]
assert_cmd = "2.0.12"
tempdir = "0.3.7"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[[bin]]
name = "ya"
path = "src/main.rs"

[[bin]]
name = "yadayada"
path = "src/bin/yadayada.rs"
required-features = ["yadayada"]

[features]
completion = ["clap_complete"]
templating = ["handlebars", "serde_json"]
gh-release = ["completion", "templating"]
yadayada = ["completion", "templating", "home"]
