[package]
name = "ya"
version = "0.1.0"
authors = ["Yousif Akbar <yousif.akbar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt   = "0.3.13"
yaml-rust   = "0.4"
log         = "0.4.14"
env_logger  = "0.8.3"
# futures = "0.3"
