[package]
name = "ya"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.11", features = ["derive"] }
colored = { version = "2.0.4" }
home = "0.5.5"
serde_derive = "1.0.171"
serde_yaml = "0.9.22"

[dev-dependencies]
assert_cmd = "2.0.11"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
