[package]
name = "ya"
version = "0.1.0"
authors = ["Yousif Akbar <yousif.akbar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt    = "0.3.13"
serde = "1.0.117"
serde_derive = "1.0.117"
serde_yaml   = "0.8.13"
log = "0.4.14"
handlebars = "3.5.4"
