name: Docs
on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ya-x86_64-unknown-linux-gnu
          path: /usr/local/bin/ya.tar.gz

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: yadayada-x86_64-unknown-linux-gnu
          path: /usr/local/bin/yadayada.tar.gz

      - name: Move `ya` and `yadayada` to appropriate locations
        run: |
          cd /usr/local/bin
          tar -xzf ya.tar.gz
          tar -xzf yadayada.tar.gz
          rm -f ya.tar.gz
          rm -f yadayada.tar.gz
          ya --version
          yadayada --version

      - name: Run docs stamp
        run: ya -c .config/ya/docs.yml stamp

      - name: "Docs check"
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Documentation is out of date. Please run 'ya -c .config/ya/docs.yml stamp' and commit the changes."
            git status
            exit 1
          fi
