name: Push

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  docs:
    needs: [build]
    name: Docs
    uses: ./.github/workflows/docs.yml
