name: Tag Test

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release_attempt_in_v3:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          path: assets

      - name: Look at the artifacts
        env:
         DOWNLOAD_PATH: ${{ steps.download.outputs.download-path }}
        run: |
            ls -R
            ls -l "$DOWNLOAD_PATH"

  release_attempt_in_v4:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          path: assets
          merge-multiple: true

      - name: Look at the artifacts
        env:
         DOWNLOAD_PATH: ${{ steps.download.outputs.download-path }}
        run: |
            ls -R
            ls -l "$DOWNLOAD_PATH"
