name: Test Tag

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: assets

      - name: Install fd
        run: |
            sudo apt update
            sudo apt install fd-find
            ln -s $(which fdfind) /usr/local/bin/fd

      - name: Prep Assets
        run: |
            fd -tf . assets -x mv '{}' assets/
            cd assets
            fd -td -x rmdir '{}'

      - name: Check Assets
        run: |
            ls -R
