name: Test Tag

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: assets

      - name: Install fd
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: sharkdp/fd
          tag: v9.0.0
          platform: linux
          arch: x86_64

      - name: Prep Assets
        run: |
            fd -tf --min-depth 2 . assets -x mv '{}' assets/
            fd -td assets -x rmdir '{}'

      - name: Check Assets
        run: |
            ls -R
